'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Configuration

    '''<summary>
    '''NETForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''linkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSaveAllConfigSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAllConfigSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GenericErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenericErrorLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtGovName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGovName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLegName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLegName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnSaveAccountParams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAccountParams As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link1name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link1name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''link1url control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link1url As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''link2name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link2name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''link2url control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link2url As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''link3name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link3name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''link3url control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link3url As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imguploader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imguploader1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''imguploader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imguploader2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSaveUIDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveUIDetails As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtRCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRCS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBillNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillNbr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMotion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotion As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTime As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVoteTot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoteTot As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResults As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPartyTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartyTotals As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOutcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOutcome As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rbDName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDName As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDistrictName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrictName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rbDNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDNbr As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDistrictNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrictNbr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMember As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlMotion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMotion1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSubjects1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubjects1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSubjects2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubjects2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtClerkName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClerkName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtClerkTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClerkTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPO1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPO1Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPO1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPO1Title As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPO2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPO2Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPO2title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPO2title As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckShowMbrStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckShowMbrStat As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckShowPartyStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckShowPartyStat As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckShowVoteTtl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckShowVoteTtl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckOptionalAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckOptionalAttendance As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckOptionalVoterStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckOptionalVoterStats As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckOptionalPartyTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckOptionalPartyTotals As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveReportData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveReportData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtVRDBName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVRDBName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVRDBUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVRDBUser As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVRDBServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVRDBServer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVRDBPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVRDBPass As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVoteDBName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoteDBName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVoteDBUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoteDBUser As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVoteDBServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoteDBServer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVoteDBPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVoteDBPass As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckYEA_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckYEA_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtYEA_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYEA_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckYEA_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckYEA_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtYeaOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYeaOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckYEA_IsEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckYEA_IsEligible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckNAY_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNAY_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNAY_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNAY_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckNAY_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNAY_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNayOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNayOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckNAY_IsEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNAY_IsEligible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckABS_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABS_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtABS_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtABS_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckABS_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABS_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAbstainOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbstainOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckABS_IsEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABS_IsEligible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckEXC_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckEXC_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtEXC_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEXC_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckEXC_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckEXC_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtExcOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExcOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckEXC_IsEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckEXC_IsEligible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckABSENT_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABSENT_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtABSENT_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtABSENT_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckABSENT_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABSENT_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAbsentOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbsentOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckABSENT_IsEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckABSENT_IsEligible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckNV_Enabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNV_Enabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNV_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNV_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckNV_IsUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNV_IsUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNVOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNVOrder As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ckNV_IsEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNV_IsEnabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveDataConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDataConfig As Global.System.Web.UI.WebControls.Button
End Class
