'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''NETForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''linkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkVoterDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkVoterDetails As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ivdet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ivdet As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkVoterStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkVoterStats As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ivstats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ivstats As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkVoterComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkVoterComp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ivcomp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ivcomp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkMemberAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMemberAttendance As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''iAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iAtt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRCSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRCSum As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ircsum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ircsum As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRCTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRCTrans As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''irctrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents irctrans As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''adminSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
