'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RollCallSummary

    '''<summary>
    '''NETForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''linkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ckAllBills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAllBills As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtSearchSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckRCSSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckRCSSort As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckLegSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckLegSort As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckYea2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckYea2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckNay2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNay2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckAbstain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAbstain2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckExc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckExc2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckAbsent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAbsent2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''l6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckNV2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckNV2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBeginDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEndDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDoReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoReport As Global.System.Web.UI.WebControls.Button
End Class
