'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VoterAttendance

    '''<summary>
    '''NETForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''linkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ckAllMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAllMembers As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBeginDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEndDate As Global.System.Web.UI.WebControls.DropDownList
End Class
